name: Deploy Henio
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Henio with bun
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: executes multiline script
        run: |
          node -v
          npm -v

      - name: list of files after checkout
        run: |
          pwd
          ls -a

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        run: npm publish --access public

      - run: npm ci
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
      # - name: Run build
      #   run: bun run build
